name: "Deployment"
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Npm
        uses: actions/setup-node@v4
        #with:
        #  node-version:
      - uses: actions/upload-pages-artifact@v3
        with:
          path: "./docs/_site/"
      - name: Install NodeJS Packages
        run: npm i
      - name: Generates static CSS files
        run: npx tailwindcss -i ./docs/input.css -o ./docs/output.css
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          #extensions: intl, mbstring, soap, sqlite3, xml, apcu, dom
          #coverage: xdebug, pcov
      - name: Generates static HTML files
        run: php bin/generator
      - name: "Archive Artifact"
        run: |
          echo ::group::Archive artifact
          tar \
            --dereference --hard-dereference \
            --directory "$INPUT_PATH" \
            -cvf "$RUNNER_TEMP/artifact.tar" \
            --exclude=.git \
            --exclude=.github \
            .
          echo ::endgroup::
          shell: /usr/bin/sh -e {0}
          env:
            INPUT_PATH: ./docs/_site
      - name: Upload artifact
        id: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.name }}
          path: ${{ runner.temp }}/artifact.tar
          retention-days: ${{ inputs.retention-days }}
          if-no-files-found: error
        
  # Deploy job
  deploy:
    # Add a dependency to the build job
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # or specific "vX.X.X" version tag for this action

